technologies blog post
zCoreGroup/zcoregroup.github.io pull request #55
Opened 2023-06-02 19:27 UTC by mbarger14

The Evolving Landscape of Government Contracting: Navigating Emerging Technologies with zCore Group

2023-06-07 02:01 UTC, michaelwnau commented
Add me for review

2023-06-07 10:44 UTC, mbarger14 commented
added

2023-06-07 10:44 UTC, mbarger14 commented
> Add me for review

added

2023-06-09 12:17 UTC, bastosmichael commented on _posts/2023-06-02-technologies-evolution-blog.md
> +Artificial intelligence has emerged as a game-changer in government contracting. With its ability to automate processes, analyze vast amounts of data, and provide valuable insights, AI is revolutioni
Add a sentence at the end about our understanding of Large Language Models (LLMs) and our usage of tools like LangChain, Tranformers python library and Qdrant Vector Databases in our own internal usage.

2023-06-09 12:19 UTC, bastosmichael commented on _posts/2023-06-02-technologies-evolution-blog.md
> +Blockchain technology holds immense promise for enhancing transparency, security, and efficiency in government contracting. The decentralized nature of blockchain allows for tamper-proof record-keepi
Add a sentence about our experience in using solidity to build DAO contracts as well as using the Open Zeppelin tools to make sure our code starts securely.

2023-06-09 12:24 UTC, bastosmichael commented on _posts/2023-06-02-technologies-evolution-blog.md
> +As government agencies rely more heavily on digital infrastructure, cybersecurity becomes an indispensable aspect of government contracting. The increasing prevalence of cyber threats necessitates a
Add a sentence about our familiarity with Dependabot dependency tracking and Snyk auditing services tied to CI/CD pipelining as a way to keep code up to date.

2023-06-09 12:32 UTC, bastosmichael requested changes
Please add the sentences described that give the paragraphs more technical detail.

2023-06-13 22:46 UTC, merged