Added zCore links to opening and  Call-To-Action paragraphs to the blogs in _insights
zCoreGroup/zcoregroup.github.io pull request #69
Opened 2023-06-08 19:06 UTC by michaelwnau

Added zCore Group link to opening paragraphs and to call-to-action paragraphs to all blogs on _insights. Where a call-to-action paragraph did not exist, paragraph was added IOW ZCG style.

This PR addresses Issue #68.

2023-06-09 12:06 UTC, bastosmichael requested changes
The user is already reading this blog post on the zCore website so sending him to the homepage feels redundant, instead create an About zCore page under Contact or something and send the user there so that they are reading about the company itself on the zcore website etc. The rest looks good.

2023-06-09 13:30 UTC, michaelwnau commented
Updated blogs with link to About page instead of Home. This required some minor edits for the context shift in the final sentence of the Call to Action paragraph, but made no significant changes to the rest of the blog. This change will also require an About page be added to the site. See Issue #72

2023-06-09 15:11 UTC, bastosmichael commented on _posts/2023-01-30-intorducing-zcore-group.md
> +[zCore Group](https://zcoregroup.com/about/) is a company that is committed to building trusted partnerships with our clients to optimize their business outcomes. Our mission is to close the collabor
Remove the zcoregroup and just do /about so that the user gets sent to the localized version of the about page, we should avoid including our URL in any links on the site in order to avoid confusion between changes made to production vs staging versions of the site etc.

2023-06-09 16:20 UTC, bastosmichael commented on _posts/2023-01-30-intorducing-zcore-group.md
> +We are a company that is committed to building trusted partnerships with our clients to optimize their business outcomes. Our mission is to close the collaboration gap between technology and federal
you need to wrap the text you want to highlight so [Learn more about us, our mission, and values:](/about).

2023-06-09 18:51 UTC, bastosmichael commented
If you change all of the [/about] placeholders you added on here to be actual links in the paragraph somewhere pointing to the current https://zcoregroup.github.io/about by just doing something like [zCore](/about) then I'll go ahead and approve this one before the weekend.

2023-06-12 14:15 UTC, bastosmichael approved these changes
:shipit:

2023-06-12 14:17 UTC, merged